solver_options:
    regularization: 1e-4
    back_end: "osqp"

stack:
    - ["LFoot", "RFoot", "Com"]

constraints: ["JointLimits", "VelocityLimits"]

JointLimits:
    type: JointLimits

VelocityLimits:
    type: VelocityLimits

LFoot:
    type: "Cartesian"
    distal_link: "l_sole"

RFoot:
    type: "Cartesian"
    distal_link: "r_sole"

Com:
    type: "Com"
    indices: [0, 1, 2]
