constraints:
    - collisions
    - joint_limits
    - velocity_limits
    - nominal_trajectory

collisions:
    max_pair_link: 20
    weight: 100

optimizer:
    iterations: 20

nominal_trajectory:
    weight: 10.0

velocity_limits:
    weight: 10.0
