constraints:
    - collisions
    - joint_limits
    - velocity_limits
    - nominal_trajectory
    - trajectory_vel
    - kinematic
    - postural

collisions:
    max_pair_link: 200
    weight: 1000

optimizer:
    iterations: 1
    num_local_vertices: 25

nominal_trajectory:
    weight: 1
    end_effectors:
        - "wheel_1"
        - "wheel_2"
        - "wheel_3"
        - "wheel_4"

velocity_limits:
    weight: 10

trajectory_vel:
    weight: 100

postural:
    weight: 1

kinematic:
    distal_links:
        - "wheel_1"
        - "wheel_2"
        - "wheel_3"
        - "wheel_4"
        - "com"
    wheel_1:
        weight: 1000
        indices: [2, 3, 4]
    wheel_2:
        weight: 1000
        indices: [2, 3, 4]
    wheel_3:
        weight: 1000
        indices: [2, 3, 4]
    wheel_4:
        weight: 1000
        indices: [2, 3, 4]
    com:
        weight: 10
        indices: [0, 1]
