constraints:
    - collisions
    - joint_limits
    # - velocity_limits
    - nominal_trajectory
    # - trajectory_vel
    - kinematic

collisions:
    max_pair_link: 150
    weight: 100

optimizer:
    iterations: 1
    num_local_vertices: 50

nominal_trajectory:
    weight: 10
    end_effectors:
        - "wheel_1"
        - "wheel_2"
        - "wheel_3"
        - "wheel_4"

velocity_limits:
    weight: 100

trajectory_vel:
    weight: 1.0

kinematic:
    distal_links:
        - "wheel_1"
        - "wheel_2"
        - "wheel_3"
        - "wheel_4"
    wheel_1:
        weight: 10000
        indices: [2]
    wheel_2:
        weight: 10000
        indices: [2]
    wheel_3:
        weight: 10000
        indices: [2]
    wheel_4:
        weight: 10000
        indices: [2]
