constraints:
    - collisions
    - joint_limits
    - velocity_limits
    - nominal_trajectory

collisions:
    max_pair_link: 20
    weight: 50

optimizer:
    iterations: 50

nominal_trajectory:
    weight: 25

velocity_limits:
    weight: 25
