constraints:
    - collisions
    - joint_limits
    - velocity_limits
    - nominal_trajectory
    # - trajectory_vel
    - kinematic

collisions:
    max_pair_link: 260
    weight: 0.01

optimizer:
    iterations: 1
    num_local_vertices: 40

nominal_trajectory:
    weight: 1
    end_effectors:
        - "wheel_1"
        - "wheel_2"
        - "wheel_3"
        - "wheel_4"

velocity_limits:
    weight: 1

trajectory_vel:
    weight: 0.01

kinematic:
    distal_links:
        - "wheel_1"
        - "wheel_2"
        - "wheel_3"
        - "wheel_4"
    wheel_1:
        weight: 100
        indices: [2]
    wheel_2:
        weight: 100
        indices: [2]
    wheel_3:
        weight: 100
        indices: [2]
    wheel_4:
        weight: 100
        indices: [2]
