constraints:
    - collisions
    # - joint_limits
    - velocity_limits
    - nominal_trajectory
    - trajectory_vel

collisions:
    max_pair_link: 50
    weight: 50

optimizer:
    iterations: 1

nominal_trajectory:
    weight: 5

velocity_limits:
    weight: 1

trajectory_vel:
    weight: 50
