constraints:
    - collisions
    # - joint_limits
    - velocity_limits
    - nominal_trajectory
    - trajectory_vel

collisions:
    max_pair_link: 100
    weight: 100

optimizer:
    iterations: 2

nominal_trajectory:
    weight: 10

velocity_limits:
    weight: 100

trajectory_vel:
    weight: 0.001
