constraints:
    - collisions
    # - joint_limits
    - velocity_limits
    - nominal_trajectory
    - trajectory_vel

collisions:
    max_pair_link: 50
    weight: 50

optimizer:
    iterations: 2

nominal_trajectory:
    weight: 50

velocity_limits:
    weight: 50

trajectory_vel:
    weight: 0.1
