state_validity_check:
    - self-collision
    # - ground_collision

self-collision:
    type: "CollisionCheck"
    include_environment: false

ground_collision:
    type: "GroundCollisionAvoidance"
    axis: [0.0, 0.0, 1.0]
    link: "ball1_tip"

RRTstar:
    GoalBias: 0.1
    KNearest: true
    Range: 1000
    
RRTConnect:
    #Range: 1.0
    #IntermediateStates: true

state_space:
    floating_base_pos_min: [-1, -1, -1]
    floating_base_pos_max: [ 10,  10,  10]
    type: "Atlas"
    alpha: 0.5233
    rho: 0.1
    epsilon: 0.1
    exploration: 0.5
