solver_options:
    regularization: 1e-4
    back_end: "qpoases"

stack:
    - ["EE"]
    
    
constraints: ["JointLimits"]

JointLimits:
    type: "JointLimits"

VelocityLimits:
    type: "VelocityLimits"

EE:
    type: "Cartesian"
    distal_link: "TCP"
    base_link: "world"
    indices: [0, 1, 2]
  #  use_body_jacobian: true